### PR TITLE
fix: error when creating edge application with module activated 

### LINKED ISSUE #141: Error when create a azion_edge_application_main_setting
I'm trying to create the resource `azion_edge_application_main_setting` with a `application_acceleration = true`, but I'm getting the following error: 

`When you create a Edge Application: ApplicationAcceleration must be false or remove from request`

In my case this generate a problem which I can't create a rule engine with a bypass cache phase and this the error: 

```
│   68: resource "azion_edge_application_rule_engine" "default" {
│
│ {"behaviors":"Unable to save this rule because to use \"Bypass Cache Phase\" you must first enable
│ Application Accelerator."}
```
Can anyone help me with this? Because I would like to know if it is possible to create a fix in an edge application to create it with an application_acceleration parameter equals to true.

Thanks in advance.

### PR DESCRIPTION
**Pull request by maxwelbm**
https://github.com/aziontech/terraform-provider-azion/issues/141

### CODE REVIEW

File: internal/data_source_dnssec.go [hunk 1]
```diff
@@ -152,9 +154,18 @@ func (d *dnsSecDataSource) Read(ctx context.Context, req datasource.ReadRequest,
 	if resp.Diagnostics.HasError() {
 		return
 	}
-	zoneId := int32(getZoneId.ValueInt64())
 
-	getDnsSec, response, err := d.client.idnsApi.DNSSECAPI.GetZoneDnsSec(ctx, zoneId).Execute() //nolint
+	zoneID32, err := utils.CheckInt64toInt32Security(getZoneId.ValueInt64())
+	if err != nil {
+		resp.Diagnostics.AddError(
+			"Error before Overflow",
```
Comment (PatrickMenoti) [inline internal/data_source_dnssec.go:161]: `Error: value exceeds the valid range`

I think the message above represent the problem better

**Review by PatrickMenoti — APPROVED** [review]

**Review by rodrigomaria — APPROVED** [review]
